image: $TOOLCHAIN_REGISTRY_IMAGE/amd64:latest

Lint:
  script:
    - golint -set_exit_status $(go list ./...)

Code Generation:
  script:
    - go generate -v ./...
    - git add :/
    - git diff --exit-code HEAD
